title: Will Barkoff
tagline: I'm Will Barkoff, a student by day and a developer by night. I'm indecisive at dusk.

collections:
  projects:
    output: true
    permalink: /projects/:name

nav-links:
  - title: Home
    url: /
  - title: Contact
    url: /contact.html
  - title: Posts
    url: /posts.html
  - title: Resume
    url: /resume.html

footer-social:
  - icon: fas fa-envelope
    url: mailto:william@barkoffusa.com
    username: william@barkoffusa.com
  - icon: fab fa-twitter
    url: https://twitter.com/willbarkoff
    username: "@willbarkoff"
  - icon: fab fa-github
    url: https://github.com/willbarkoff
    username: "@willbarkoff"
  - icon: fab fa-linkedin-in
    url: https://linkedin.com/in/willbarkoff
    username: "LinkedIn"
  - icon: fas fa-key
    url: /key.html
    username: "PGP Key"

footer-projects:
  - name: MyHomeworkSpace
    url: https://myhomework.space
  - name: Honor with Code
    url: https://honorwithcode.org

footer-resources:
  - name: Website Source Code
    url: https://github.com/willbarkoff/willbarkoff.github.io
  - name: Contact Me
    url: /contact.html
  - name: PGP Key
    url: /key.html

markdown: kramdown
kramdown:
  math_engine: katex

repository: "willbarkoff/willbarkoff.github.io"

sass:
  style: compressed

permalink: /:categories/:year/:month/:day/:title

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-feed
